version: 0.0
os: linux
files:
   - source: /charts
     destination: /home/ubuntu/charts
     overwrite: true
permissions:
   - object: /home/ubuntu/charts
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: Scripts/installapache.sh
      runas: root
    - location: Scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: Scripts/ionic.sh
      runas: root
    - location: Scripts/movefiles.sh
      runas: root
    - location: Scripts/restartapache.sh
      runas: root
   ValidateService:
    - location: Scripts/pushtos3.sh
      runas: root
