version: 0.0
os: linux
files:
   - source: /charts
     destination: /var/www/html
     overwrite: true
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: Scripts/installapache.sh
      runas: ubuntu
    - location: Scripts/startapache.sh
      runas: ubuntu
   AfterInstall:
    - location: Scripts/restartapache.sh
      runas: ubuntu
